### ISSUE TITLE
[KATANA] Tracking issue for persistent storage

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#1028]
This is a tracking issue for implementing persistent storage in `katana`. 

Database choice is `libmdbx`. We will use `reth`'s fork of [`libdmdbx`](https://github.com/paradigmxyz/reth/tree/main/crates/storage/libmdbx-rs) .

```[tasklist]
### Tasks
- [ ] https://github.com/dojoengine/dojo/issues/1144
- [ ] https://github.com/dojoengine/dojo/issues/1145
- [ ] https://github.com/dojoengine/dojo/issues/1146
```

**Comment by kariy** [comment]
Feature added in #1440
