### ISSUE TITLE
tracking: katana metrics 

### ISSUE THREAD

**Issue by grudich** [dojoengine/dojo#1369]
Add metrics throughout katana

```[tasklist]
### Tasks
- [ ] https://github.com/dojoengine/dojo/pull/1719
- [ ] https://github.com/dojoengine/dojo/pull/1726
- [ ] https://github.com/dojoengine/dojo/pull/1728
- [ ] https://github.com/dojoengine/dojo/pull/1791
- [ ] https://github.com/dojoengine/dojo/pull/1818
```

**Comment by glihm** [comment]
@kariy would consider this as done due to all PRs being merged, please don't hesitate to re-open as needed.
