### ISSUE TITLE
[SDKs] Unity Client

### ISSUE THREAD

**Issue by grudich** [dojoengine/dojo#1391]
```[tasklist]
### Tasks
- [x] WebGL Torii support
- [x] WebGL Starknet support
- [x] Model codegen using cainome
- [ ] System codegen using cainome
- [ ] Verify support for android and iOS
```
