### ISSUE TITLE
[Torii] gRPC entity state update api

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#689]
Extend torii to provide a gRPC api in addition to the existing graphql api. gRPC provides an efficient api for high throughput communication. The response payload should be generic enough to support any entity state update and complete enough to support reconstruction of the typed entities on the client.

```[tasklist]
### Tasks
- [ ] Define a generic protobuf for communicating state changes for an entities components
- [ ] Define a Get RPC to return the latest state changes given a cursor and limit
- [ ] Support long polling the state update rpc
```

The existing Graphql API is defined here: https://github.com/dojoengine/dojo/tree/main/crates/torii/src/graphql

**Comment by shuimuliang** [comment]
1. Define a generic protobuf for communicating state changes for an entities components
  - [ ] torii-grpc-proto
  - [ ] torii-grpc-server
  - [ ] torii-grpc-client(rs)

2.  implement unary methods to get the latest state changes for an entities components

3.  implement streaming methods to poll the state update, e.g:
- [ ]  A new archetype has been created.
- [ ]  An entity has been inserted into an archetype.
- [ ]  An entity has been removed from an archetype.
@tarrencev 

Q: Does gRPC use the same port with the GraphQL service (8080)? Probably not. (8081 or 9000)

**Comment by ponderingdemocritus** [comment]
@shuimuliang this is a big and important issue - do you have the bandwidth to complete in a reasonable time? If not, lets split this up.

**Comment by shuimuliang** [comment]
plan to finish in 2 weeks.

please split it into 3 issues with branches:
1. Define a gPRC protocol for Torri.
2. implement gRPC unary methods to get the latest state changes
3. implement gRPC streaming methods to poll the state update
