### ISSUE TITLE
[KATANA] Update `katana` to support JSON-RPC v0.4.0 spec

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#816]
Update `katana` to support version [0.4.0](https://github.com/starkware-libs/starknet-specs/releases/tag/v0.4.0) of the RPC spec. 

```[tasklist]
### Tasks
- [x] Implement new endpoint `starknet_estimateMessageFee`
- [x] Split status into `execution_status` and `finality_status`
- [x] Invoke v0 transaction: remove nonce and rename sender_address to contract_address
```
